def foo(n):
    fruit_list = [
        "kiwi",
        "pear",
        "kiwi",
        "banana",
        "melon",
        "banana",
        "melon",
        "pineapple",
        "apple",
        "pineapple",
        "cucumber",
        "pineapple",
        "cucumber",
        "orange",
        "grape",
        "orange",
        "grape",
        "apple",
        "grape",
        "cherry",
        "pear",
        "cherry",
        "pear",
        "kiwi",
        "banana",
        "kiwi",
        "apple",
        "melon",
        "banana",
        "melon",
        "pineapple",
        "melon",
        "pineapple",
        "cucumber",
        "orange",
        "apple",
        "orange",
        "grape",
        "orange",
        "grape",
        "cherry",
        "pear",
        "cherry",
        "pear",
        "apple",
        "pear",
        "kiwi",
        "banana",
        "kiwi",
        "banana",
        "melon",
        "pineapple",
        "melon",
        "apple",
        "cucumber",
        "pineapple",
        "cucumber",
        "orange",
        "cucumber",
        "orange",
        "grape",
        "cherry",
        "apple",
        "cherry",
        "pear",
        "cherry",
        "pear",
        "kiwi",
        "pear",
        "kiwi",
        "banana",
        "apple",
        "banana",
        "melon",
        "pineapple",
        "melon",
        "pineapple",
        "cucumber",
        "pineapple",
        "cucumber",
        "apple",
        "grape",
        "orange",
        "grape",
        "cherry",
        "grape",
        "cherry",
        "pear",
        "cherry",
        "apple",
        "kiwi",
        "banana",
        "kiwi",
        "banana",
        "melon",
        "banana",
        "melon",
        "pineapple",
        "apple",
        "pineapple",
    ]

    result = n

    while result > 100:
        minus = 0
        for i in range(len(str(n)) - 1, -1, -1):
            minus += n // (10**i)
            n %= 10**i
        result -= minus
        n = result

    result = fruit_list[result]

    return result
